/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TelecomDtoEmbed } from "./TelecomDtoEmbed"

export class AddressDto {
  constructor(json: JSON | any) {
    Object.assign(this as AddressDto, json)
  }

  objectType?: string
  addressType?: AddressDto.AddressDtoAddressTypeEnum
  descr?: string
  street?: string
  houseNumber?: string
  postboxNumber?: string
  postalCode?: string
  city?: string
  country?: string
  encryptedSelf?: string
  note?: string
  telecoms?: Array<TelecomDtoEmbed>
}
export namespace AddressDto {
  export type AddressDtoAddressTypeEnum =
    | "home"
    | "work"
    | "vacation"
    | "hospital"
    | "clinic"
    | "hq"
    | "other"
  export const AddressDtoAddressTypeEnum = {
    Home: "home" as AddressDtoAddressTypeEnum,
    Work: "work" as AddressDtoAddressTypeEnum,
    Vacation: "vacation" as AddressDtoAddressTypeEnum,
    Hospital: "hospital" as AddressDtoAddressTypeEnum,
    Clinic: "clinic" as AddressDtoAddressTypeEnum,
    Hq: "hq" as AddressDtoAddressTypeEnum,
    Other: "other" as AddressDtoAddressTypeEnum
  }
}
