/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TelecomDto } from "./TelecomDto"

import { decodeBase64 } from "./ModelHelper"

export class AddressDto {
  constructor(json: JSON | any) {
    Object.assign(this as AddressDto, json)
  }

  addressType?: AddressDto.AddressTypeEnum
  descr?: string
  street?: string
  houseNumber?: string
  postboxNumber?: string
  postalCode?: string
  city?: string
  country?: string
  note?: string
  telecoms?: Array<TelecomDto>
  encryptedSelf?: string
}
export namespace AddressDto {
  export type AddressTypeEnum =
    | "home"
    | "work"
    | "vacation"
    | "hospital"
    | "clinic"
    | "hq"
    | "other"
  export const AddressTypeEnum = {
    Home: "home" as AddressTypeEnum,
    Work: "work" as AddressTypeEnum,
    Vacation: "vacation" as AddressTypeEnum,
    Hospital: "hospital" as AddressTypeEnum,
    Clinic: "clinic" as AddressTypeEnum,
    Hq: "hq" as AddressTypeEnum,
    Other: "other" as AddressTypeEnum
  }
}
