/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDto } from "./AddressDto"
import { CalendarItemTagDto } from "./CalendarItemTagDto"
import { CodeDto } from "./CodeDto"
import { DelegationDto } from "./DelegationDto"
import { FlowItemDto } from "./FlowItemDto"

export class CalendarItemDto {
  constructor(json: JSON | any) {
    Object.assign(this as CalendarItemDto, json)
  }

  id?: string
  rev?: string
  deletionDate?: number
  created?: number
  modified?: number
  endOfLife?: number
  author?: string
  responsible?: string
  medicalLocationId?: string
  encryptedSelf?: string
  codes?: Array<CodeDto>
  tags?: Array<CodeDto>
  secretForeignKeys?: Array<string>
  cryptedForeignKeys?: { [key: string]: Array<DelegationDto> }
  delegations?: { [key: string]: Array<DelegationDto> }
  encryptionKeys?: { [key: string]: Array<DelegationDto> }
  title?: string
  calendarItemTypeId?: string
  masterCalendarItemId?: string
  patientId?: string
  important?: boolean
  homeVisit?: boolean
  phoneNumber?: string
  placeId?: string
  address?: AddressDto
  addressText?: string
  startTime?: number
  endTime?: number
  confirmationTime?: number
  confirmationId?: string
  duration?: number
  allDay?: boolean
  details?: string
  agendaId?: string
  wasMigrated?: boolean
  meetingTags?: Array<CalendarItemTagDto>
  flowItem?: FlowItemDto
}
