/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeStub } from "./CodeStub"

export class CareTeamMemberDto {
  constructor(json: JSON | any) {
    Object.assign(this as CareTeamMemberDto, json)
  }

  id?: string
  careTeamMemberType?: CareTeamMemberDto.CareTeamMemberDtoCareTeamMemberTypeEnum
  healthcarePartyId?: string
  quality?: CodeStub
}
export namespace CareTeamMemberDto {
  export type CareTeamMemberDtoCareTeamMemberTypeEnum = "physician" | "specialist" | "other"
  export const CareTeamMemberDtoCareTeamMemberTypeEnum = {
    Physician: "physician" as CareTeamMemberDtoCareTeamMemberTypeEnum,
    Specialist: "specialist" as CareTeamMemberDtoCareTeamMemberTypeEnum,
    Other: "other" as CareTeamMemberDtoCareTeamMemberTypeEnum
  }
}
