/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Periodicity } from "./Periodicity"

export class CodeDto {
  constructor(json: JSON | any) {
    Object.assign(this as CodeDto, json)
  }

  id?: string
  rev?: string
  deletionDate?: number
  parent?: string
  author?: string
  regions?: Array<string>
  type?: string
  version?: string
  code?: string
  level?: number
  label?: { [key: string]: string }
  searchTerms?: { [key: string]: Array<string> }
  links?: Array<string>
  qualifiedLinks?: { [key: string]: Array<string> }
  flags?: Array<CodeDto.CodeDtoFlagsEnum>
  data?: string
  appendices?: { [key: string]: string }
  periodicity?: Array<Periodicity>
  disabled?: boolean
}
export namespace CodeDto {
  export type CodeDtoFlagsEnum =
    | "male_only"
    | "female_only"
    | "deptkinesitherapy"
    | "deptnursing"
    | "deptgeneralpractice"
    | "deptsocialworker"
    | "deptpsychology"
    | "deptadministrative"
    | "deptdietetics"
    | "deptspeechtherapy"
    | "deptdentistry"
    | "deptoccupationaltherapy"
    | "depthealthcare"
    | "deptgynecology"
    | "deptpediatry"
    | "deptalgology"
    | "deptanatomopathology"
    | "deptanesthesiology"
    | "deptbacteriology"
    | "deptcardiacsurgery"
    | "deptcardiology"
    | "deptchildandadolescentpsychiatry"
    | "deptdermatology"
    | "deptdiabetology"
    | "deptemergency"
    | "deptendocrinology"
    | "deptgastroenterology"
    | "deptgenetics"
    | "deptgeriatry"
    | "depthandsurgery"
    | "depthematology"
    | "deptinfectiousdisease"
    | "deptintensivecare"
    | "deptlaboratory"
    | "deptmajorburns"
    | "deptmaxillofacialsurgery"
    | "deptmedicine"
    | "deptmolecularbiology"
    | "deptneonatalogy"
    | "deptnephrology"
    | "deptneurology"
    | "deptneurosurgery"
    | "deptnte"
    | "deptnuclear"
    | "deptnutritiondietetics"
    | "deptobstetrics"
    | "deptoncology"
    | "deptophtalmology"
    | "deptorthopedy"
    | "deptpalliativecare"
    | "deptpediatricintensivecare"
    | "deptpediatricsurgery"
    | "deptpharmacy"
    | "deptphysicalmedecine"
    | "deptphysiotherapy"
    | "deptplasticandreparatorysurgery"
    | "deptpneumology"
    | "deptpodiatry"
    | "deptpsychiatry"
    | "deptradiology"
    | "deptradiotherapy"
    | "deptrevalidation"
    | "deptrheumatology"
    | "deptrhumatology"
    | "deptsenology"
    | "deptsocialservice"
    | "deptsportsmedecine"
    | "deptstomatology"
    | "deptsurgery"
    | "deptthoracicsurgery"
    | "depttoxicology"
    | "depttropicalmedecine"
    | "depturology"
    | "deptvascularsurgery"
    | "deptvisceraldigestiveabdominalsurgery"
    | "depttransplantsurgery"
    | "deptpercutaneous"
    | "deptchildbirth"
  export const CodeDtoFlagsEnum = {
    MaleOnly: "male_only" as CodeDtoFlagsEnum,
    FemaleOnly: "female_only" as CodeDtoFlagsEnum,
    Deptkinesitherapy: "deptkinesitherapy" as CodeDtoFlagsEnum,
    Deptnursing: "deptnursing" as CodeDtoFlagsEnum,
    Deptgeneralpractice: "deptgeneralpractice" as CodeDtoFlagsEnum,
    Deptsocialworker: "deptsocialworker" as CodeDtoFlagsEnum,
    Deptpsychology: "deptpsychology" as CodeDtoFlagsEnum,
    Deptadministrative: "deptadministrative" as CodeDtoFlagsEnum,
    Deptdietetics: "deptdietetics" as CodeDtoFlagsEnum,
    Deptspeechtherapy: "deptspeechtherapy" as CodeDtoFlagsEnum,
    Deptdentistry: "deptdentistry" as CodeDtoFlagsEnum,
    Deptoccupationaltherapy: "deptoccupationaltherapy" as CodeDtoFlagsEnum,
    Depthealthcare: "depthealthcare" as CodeDtoFlagsEnum,
    Deptgynecology: "deptgynecology" as CodeDtoFlagsEnum,
    Deptpediatry: "deptpediatry" as CodeDtoFlagsEnum,
    Deptalgology: "deptalgology" as CodeDtoFlagsEnum,
    Deptanatomopathology: "deptanatomopathology" as CodeDtoFlagsEnum,
    Deptanesthesiology: "deptanesthesiology" as CodeDtoFlagsEnum,
    Deptbacteriology: "deptbacteriology" as CodeDtoFlagsEnum,
    Deptcardiacsurgery: "deptcardiacsurgery" as CodeDtoFlagsEnum,
    Deptcardiology: "deptcardiology" as CodeDtoFlagsEnum,
    Deptchildandadolescentpsychiatry: "deptchildandadolescentpsychiatry" as CodeDtoFlagsEnum,
    Deptdermatology: "deptdermatology" as CodeDtoFlagsEnum,
    Deptdiabetology: "deptdiabetology" as CodeDtoFlagsEnum,
    Deptemergency: "deptemergency" as CodeDtoFlagsEnum,
    Deptendocrinology: "deptendocrinology" as CodeDtoFlagsEnum,
    Deptgastroenterology: "deptgastroenterology" as CodeDtoFlagsEnum,
    Deptgenetics: "deptgenetics" as CodeDtoFlagsEnum,
    Deptgeriatry: "deptgeriatry" as CodeDtoFlagsEnum,
    Depthandsurgery: "depthandsurgery" as CodeDtoFlagsEnum,
    Depthematology: "depthematology" as CodeDtoFlagsEnum,
    Deptinfectiousdisease: "deptinfectiousdisease" as CodeDtoFlagsEnum,
    Deptintensivecare: "deptintensivecare" as CodeDtoFlagsEnum,
    Deptlaboratory: "deptlaboratory" as CodeDtoFlagsEnum,
    Deptmajorburns: "deptmajorburns" as CodeDtoFlagsEnum,
    Deptmaxillofacialsurgery: "deptmaxillofacialsurgery" as CodeDtoFlagsEnum,
    Deptmedicine: "deptmedicine" as CodeDtoFlagsEnum,
    Deptmolecularbiology: "deptmolecularbiology" as CodeDtoFlagsEnum,
    Deptneonatalogy: "deptneonatalogy" as CodeDtoFlagsEnum,
    Deptnephrology: "deptnephrology" as CodeDtoFlagsEnum,
    Deptneurology: "deptneurology" as CodeDtoFlagsEnum,
    Deptneurosurgery: "deptneurosurgery" as CodeDtoFlagsEnum,
    Deptnte: "deptnte" as CodeDtoFlagsEnum,
    Deptnuclear: "deptnuclear" as CodeDtoFlagsEnum,
    Deptnutritiondietetics: "deptnutritiondietetics" as CodeDtoFlagsEnum,
    Deptobstetrics: "deptobstetrics" as CodeDtoFlagsEnum,
    Deptoncology: "deptoncology" as CodeDtoFlagsEnum,
    Deptophtalmology: "deptophtalmology" as CodeDtoFlagsEnum,
    Deptorthopedy: "deptorthopedy" as CodeDtoFlagsEnum,
    Deptpalliativecare: "deptpalliativecare" as CodeDtoFlagsEnum,
    Deptpediatricintensivecare: "deptpediatricintensivecare" as CodeDtoFlagsEnum,
    Deptpediatricsurgery: "deptpediatricsurgery" as CodeDtoFlagsEnum,
    Deptpharmacy: "deptpharmacy" as CodeDtoFlagsEnum,
    Deptphysicalmedecine: "deptphysicalmedecine" as CodeDtoFlagsEnum,
    Deptphysiotherapy: "deptphysiotherapy" as CodeDtoFlagsEnum,
    Deptplasticandreparatorysurgery: "deptplasticandreparatorysurgery" as CodeDtoFlagsEnum,
    Deptpneumology: "deptpneumology" as CodeDtoFlagsEnum,
    Deptpodiatry: "deptpodiatry" as CodeDtoFlagsEnum,
    Deptpsychiatry: "deptpsychiatry" as CodeDtoFlagsEnum,
    Deptradiology: "deptradiology" as CodeDtoFlagsEnum,
    Deptradiotherapy: "deptradiotherapy" as CodeDtoFlagsEnum,
    Deptrevalidation: "deptrevalidation" as CodeDtoFlagsEnum,
    Deptrheumatology: "deptrheumatology" as CodeDtoFlagsEnum,
    Deptrhumatology: "deptrhumatology" as CodeDtoFlagsEnum,
    Deptsenology: "deptsenology" as CodeDtoFlagsEnum,
    Deptsocialservice: "deptsocialservice" as CodeDtoFlagsEnum,
    Deptsportsmedecine: "deptsportsmedecine" as CodeDtoFlagsEnum,
    Deptstomatology: "deptstomatology" as CodeDtoFlagsEnum,
    Deptsurgery: "deptsurgery" as CodeDtoFlagsEnum,
    Deptthoracicsurgery: "deptthoracicsurgery" as CodeDtoFlagsEnum,
    Depttoxicology: "depttoxicology" as CodeDtoFlagsEnum,
    Depttropicalmedecine: "depttropicalmedecine" as CodeDtoFlagsEnum,
    Depturology: "depturology" as CodeDtoFlagsEnum,
    Deptvascularsurgery: "deptvascularsurgery" as CodeDtoFlagsEnum,
    Deptvisceraldigestiveabdominalsurgery: "deptvisceraldigestiveabdominalsurgery" as CodeDtoFlagsEnum,
    Depttransplantsurgery: "depttransplantsurgery" as CodeDtoFlagsEnum,
    Deptpercutaneous: "deptpercutaneous" as CodeDtoFlagsEnum,
    Deptchildbirth: "deptchildbirth" as CodeDtoFlagsEnum
  }
}
