/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Attachment } from "./Attachment"
import { Periodicity } from "./Periodicity"
import { RevisionInfo } from "./RevisionInfo"

export class Code {
  constructor(json: JSON | any) {
    Object.assign(this as Code, json)
  }

  author?: string
  regions?: Array<string>
  periodicity?: Array<Periodicity>
  type?: string
  code?: string
  version?: string
  level?: number
  label?: { [key: string]: string }
  links?: Array<string>
  qualifiedLinks?: { [key: string]: Array<string> }
  flags?: Array<Code.CodeFlagsEnum>
  searchTerms?: { [key: string]: Array<string> }
  data?: string
  appendices?: { [key: string]: string }
  disabled?: boolean
  attachments?: { [key: string]: Attachment }
  deleted?: number
  id?: string
  rev?: string
  revsInfo?: Array<RevisionInfo>
  conflicts?: Array<string>
  javaType?: string
  revHistory?: { [key: string]: string }
}
export namespace Code {
  export type CodeFlagsEnum =
    | "male_only"
    | "female_only"
    | "deptkinesitherapy"
    | "deptnursing"
    | "deptgeneralpractice"
    | "deptsocialworker"
    | "deptpsychology"
    | "deptadministrative"
    | "deptdietetics"
    | "deptspeechtherapy"
    | "deptdentistry"
    | "deptoccupationaltherapy"
    | "depthealthcare"
    | "deptgynecology"
    | "deptpediatry"
    | "deptalgology"
    | "deptanatomopathology"
    | "deptanesthesiology"
    | "deptbacteriology"
    | "deptcardiacsurgery"
    | "deptcardiology"
    | "deptchildandadolescentpsychiatry"
    | "deptdermatology"
    | "deptdiabetology"
    | "deptemergency"
    | "deptendocrinology"
    | "deptgastroenterology"
    | "deptgenetics"
    | "deptgeriatry"
    | "depthandsurgery"
    | "depthematology"
    | "deptinfectiousdisease"
    | "deptintensivecare"
    | "deptlaboratory"
    | "deptmajorburns"
    | "deptmaxillofacialsurgery"
    | "deptmedicine"
    | "deptmolecularbiology"
    | "deptneonatalogy"
    | "deptnephrology"
    | "deptneurology"
    | "deptneurosurgery"
    | "deptnte"
    | "deptnuclear"
    | "deptnutritiondietetics"
    | "deptobstetrics"
    | "deptoncology"
    | "deptophtalmology"
    | "deptorthopedy"
    | "deptpalliativecare"
    | "deptpediatricintensivecare"
    | "deptpediatricsurgery"
    | "deptpharmacy"
    | "deptphysicalmedecine"
    | "deptphysiotherapy"
    | "deptplasticandreparatorysurgery"
    | "deptpneumology"
    | "deptpodiatry"
    | "deptpsychiatry"
    | "deptradiology"
    | "deptradiotherapy"
    | "deptrevalidation"
    | "deptrheumatology"
    | "deptrhumatology"
    | "deptsenology"
    | "deptsocialservice"
    | "deptsportsmedecine"
    | "deptstomatology"
    | "deptsurgery"
    | "deptthoracicsurgery"
    | "depttoxicology"
    | "depttropicalmedecine"
    | "depturology"
    | "deptvascularsurgery"
    | "deptvisceraldigestiveabdominalsurgery"
    | "depttransplantsurgery"
    | "deptpercutaneous"
    | "deptchildbirth"
  export const CodeFlagsEnum = {
    MaleOnly: "male_only" as CodeFlagsEnum,
    FemaleOnly: "female_only" as CodeFlagsEnum,
    Deptkinesitherapy: "deptkinesitherapy" as CodeFlagsEnum,
    Deptnursing: "deptnursing" as CodeFlagsEnum,
    Deptgeneralpractice: "deptgeneralpractice" as CodeFlagsEnum,
    Deptsocialworker: "deptsocialworker" as CodeFlagsEnum,
    Deptpsychology: "deptpsychology" as CodeFlagsEnum,
    Deptadministrative: "deptadministrative" as CodeFlagsEnum,
    Deptdietetics: "deptdietetics" as CodeFlagsEnum,
    Deptspeechtherapy: "deptspeechtherapy" as CodeFlagsEnum,
    Deptdentistry: "deptdentistry" as CodeFlagsEnum,
    Deptoccupationaltherapy: "deptoccupationaltherapy" as CodeFlagsEnum,
    Depthealthcare: "depthealthcare" as CodeFlagsEnum,
    Deptgynecology: "deptgynecology" as CodeFlagsEnum,
    Deptpediatry: "deptpediatry" as CodeFlagsEnum,
    Deptalgology: "deptalgology" as CodeFlagsEnum,
    Deptanatomopathology: "deptanatomopathology" as CodeFlagsEnum,
    Deptanesthesiology: "deptanesthesiology" as CodeFlagsEnum,
    Deptbacteriology: "deptbacteriology" as CodeFlagsEnum,
    Deptcardiacsurgery: "deptcardiacsurgery" as CodeFlagsEnum,
    Deptcardiology: "deptcardiology" as CodeFlagsEnum,
    Deptchildandadolescentpsychiatry: "deptchildandadolescentpsychiatry" as CodeFlagsEnum,
    Deptdermatology: "deptdermatology" as CodeFlagsEnum,
    Deptdiabetology: "deptdiabetology" as CodeFlagsEnum,
    Deptemergency: "deptemergency" as CodeFlagsEnum,
    Deptendocrinology: "deptendocrinology" as CodeFlagsEnum,
    Deptgastroenterology: "deptgastroenterology" as CodeFlagsEnum,
    Deptgenetics: "deptgenetics" as CodeFlagsEnum,
    Deptgeriatry: "deptgeriatry" as CodeFlagsEnum,
    Depthandsurgery: "depthandsurgery" as CodeFlagsEnum,
    Depthematology: "depthematology" as CodeFlagsEnum,
    Deptinfectiousdisease: "deptinfectiousdisease" as CodeFlagsEnum,
    Deptintensivecare: "deptintensivecare" as CodeFlagsEnum,
    Deptlaboratory: "deptlaboratory" as CodeFlagsEnum,
    Deptmajorburns: "deptmajorburns" as CodeFlagsEnum,
    Deptmaxillofacialsurgery: "deptmaxillofacialsurgery" as CodeFlagsEnum,
    Deptmedicine: "deptmedicine" as CodeFlagsEnum,
    Deptmolecularbiology: "deptmolecularbiology" as CodeFlagsEnum,
    Deptneonatalogy: "deptneonatalogy" as CodeFlagsEnum,
    Deptnephrology: "deptnephrology" as CodeFlagsEnum,
    Deptneurology: "deptneurology" as CodeFlagsEnum,
    Deptneurosurgery: "deptneurosurgery" as CodeFlagsEnum,
    Deptnte: "deptnte" as CodeFlagsEnum,
    Deptnuclear: "deptnuclear" as CodeFlagsEnum,
    Deptnutritiondietetics: "deptnutritiondietetics" as CodeFlagsEnum,
    Deptobstetrics: "deptobstetrics" as CodeFlagsEnum,
    Deptoncology: "deptoncology" as CodeFlagsEnum,
    Deptophtalmology: "deptophtalmology" as CodeFlagsEnum,
    Deptorthopedy: "deptorthopedy" as CodeFlagsEnum,
    Deptpalliativecare: "deptpalliativecare" as CodeFlagsEnum,
    Deptpediatricintensivecare: "deptpediatricintensivecare" as CodeFlagsEnum,
    Deptpediatricsurgery: "deptpediatricsurgery" as CodeFlagsEnum,
    Deptpharmacy: "deptpharmacy" as CodeFlagsEnum,
    Deptphysicalmedecine: "deptphysicalmedecine" as CodeFlagsEnum,
    Deptphysiotherapy: "deptphysiotherapy" as CodeFlagsEnum,
    Deptplasticandreparatorysurgery: "deptplasticandreparatorysurgery" as CodeFlagsEnum,
    Deptpneumology: "deptpneumology" as CodeFlagsEnum,
    Deptpodiatry: "deptpodiatry" as CodeFlagsEnum,
    Deptpsychiatry: "deptpsychiatry" as CodeFlagsEnum,
    Deptradiology: "deptradiology" as CodeFlagsEnum,
    Deptradiotherapy: "deptradiotherapy" as CodeFlagsEnum,
    Deptrevalidation: "deptrevalidation" as CodeFlagsEnum,
    Deptrheumatology: "deptrheumatology" as CodeFlagsEnum,
    Deptrhumatology: "deptrhumatology" as CodeFlagsEnum,
    Deptsenology: "deptsenology" as CodeFlagsEnum,
    Deptsocialservice: "deptsocialservice" as CodeFlagsEnum,
    Deptsportsmedecine: "deptsportsmedecine" as CodeFlagsEnum,
    Deptstomatology: "deptstomatology" as CodeFlagsEnum,
    Deptsurgery: "deptsurgery" as CodeFlagsEnum,
    Deptthoracicsurgery: "deptthoracicsurgery" as CodeFlagsEnum,
    Depttoxicology: "depttoxicology" as CodeFlagsEnum,
    Depttropicalmedecine: "depttropicalmedecine" as CodeFlagsEnum,
    Depturology: "depturology" as CodeFlagsEnum,
    Deptvascularsurgery: "deptvascularsurgery" as CodeFlagsEnum,
    Deptvisceraldigestiveabdominalsurgery: "deptvisceraldigestiveabdominalsurgery" as CodeFlagsEnum,
    Depttransplantsurgery: "depttransplantsurgery" as CodeFlagsEnum,
    Deptpercutaneous: "deptpercutaneous" as CodeFlagsEnum,
    Deptchildbirth: "deptchildbirth" as CodeFlagsEnum
  }
}
