/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MeasureDto } from "./MeasureDto"
import { MedicationDto } from "./MedicationDto"

export class ContentDto {
  constructor(json: JSON | any) {
    Object.assign(this as ContentDto, json)
  }

  stringValue?: string
  numberValue?: number
  booleanValue?: boolean
  instantValue?: number
  fuzzyDateValue?: number
  binaryValue?: Array<string>
  documentId?: string
  measureValue?: MeasureDto
  medicationValue?: MedicationDto
}
