/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HealthcareParty } from "./HealthcareParty"
import { Replication } from "./Replication"
import { User } from "./User"

/**
 * initialisationData is an object that contains the initial replications (target must be an internalTarget of value base, healthdata or patient) and the users and healthcare parties to be created
 */
import { decodeBase64 } from "./ModelHelper"

export class DatabaseInitialisation {
  constructor(json: JSON | any) {
    Object.assign(this as DatabaseInitialisation, json)
  }

  users?: Array<User>
  healthcareParties?: Array<HealthcareParty>
  replication?: Replication
}
