/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeStub } from "./CodeStub"
import { DocumentGroup } from "./DocumentGroup"

import { decodeBase64 } from "./ModelHelper"

export class DocumentTemplate {
  constructor(json: JSON | any) {
    Object.assign(
      this as DocumentTemplate,
      json,
      json.attachment ? { attachment: decodeBase64(json.attachment) } : {}
    )
  }

  id?: string
  rev?: string
  created?: number
  modified?: number
  author?: string
  responsible?: string
  medicalLocationId?: string
  tags?: Array<CodeStub>
  codes?: Array<CodeStub>
  endOfLife?: number
  deletionDate?: number
  attachment?: ArrayBuffer
  mainUti?: string
  name?: string
  otherUtis?: Array<string>
  attachmentId?: string
  version?: DocumentTemplate.VersionEnum
  owner?: string
  guid?: string
  group?: DocumentGroup
  descr?: string
  disabled?: string
  specialty?: CodeStub
}
export namespace DocumentTemplate {
  export type VersionEnum = "V1_0_0"
  export const VersionEnum = {
    _0: "V1_0_0" as VersionEnum
  }
}
