/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeStubDto } from "./CodeStubDto"
import { DocumentGroupDto } from "./DocumentGroupDto"

export class DocumentTemplateDto {
  constructor(json: JSON | any) {
    Object.assign(this as DocumentTemplateDto, json)
  }

  id?: string
  rev?: string
  created?: number
  modified?: number
  author?: string
  responsible?: string
  medicalLocationId?: string
  tags?: Array<CodeStubDto>
  codes?: Array<CodeStubDto>
  endOfLife?: number
  deletionDate?: number
  attachment?: Array<string>
  mainUti?: string
  name?: string
  otherUtis?: Array<string>
  attachmentId?: string
  version?: DocumentTemplateDto.VersionEnum
  owner?: string
  guid?: string
  group?: DocumentGroupDto
  descr?: string
  disabled?: string
  specialty?: CodeStubDto
}
export namespace DocumentTemplateDto {
  export type VersionEnum = "V1_0_0"
  export const VersionEnum = {
    _0: "V1_0_0" as VersionEnum
  }
}
