/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Attachment } from "./Attachment"
import { RevisionInfo } from "./RevisionInfo"

export class EntityReference {
  constructor(json: JSON | any) {
    Object.assign(this as EntityReference, json)
  }

  id?: string
  rev?: string
  deleted?: number
  docId?: string
  attachments?: { [key: string]: Attachment }
  revsInfo?: Array<RevisionInfo>
  conflicts?: Array<string>
  revHistory?: { [key: string]: string }
  javaType?: string
}
