/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FilterDto } from "./FilterDto"
import { Predicate } from "./Predicate"

export class FilterChain {
  constructor(json: JSON | any) {
    Object.assign(this as FilterChain, json)
  }

  filter?: FilterDto
  predicate?: Predicate
}
