/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ValorisationDto } from "./ValorisationDto"

export class FlatRateTarificationDto {
  constructor(json: JSON | any) {
    Object.assign(this as FlatRateTarificationDto, json)
  }

  code?: string
  label?: { [key: string]: string }
  valorisations?: Array<ValorisationDto>
  flatRateType?: FlatRateTarificationDto.FlatRateTarificationDtoFlatRateTypeEnum
}
export namespace FlatRateTarificationDto {
  export type FlatRateTarificationDtoFlatRateTypeEnum = "physician" | "physiotherapist" | "nurse"
  export const FlatRateTarificationDtoFlatRateTypeEnum = {
    Physician: "physician" as FlatRateTarificationDtoFlatRateTypeEnum,
    Physiotherapist: "physiotherapist" as FlatRateTarificationDtoFlatRateTypeEnum,
    Nurse: "nurse" as FlatRateTarificationDtoFlatRateTypeEnum
  }
}
