/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class Formula {
  constructor(json: JSON | any) {
    Object.assign(this as Formula, json)
  }

  value?: string
  lifecycle?: Formula.FormulaLifecycleEnum
}
export namespace Formula {
  export type FormulaLifecycleEnum = "OnCreate" | "OnLoad" | "OnChange" | "OnSave" | "OnDestroy"
  export const FormulaLifecycleEnum = {
    OnCreate: "OnCreate" as FormulaLifecycleEnum,
    OnLoad: "OnLoad" as FormulaLifecycleEnum,
    OnChange: "OnChange" as FormulaLifecycleEnum,
    OnSave: "OnSave" as FormulaLifecycleEnum,
    OnDestroy: "OnDestroy" as FormulaLifecycleEnum
  }
}
