/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeStubDto } from "./CodeStubDto"
import { DocumentGroupDto } from "./DocumentGroupDto"
import { FormLayout } from "./FormLayout"

import { decodeBase64 } from "./ModelHelper"

export class FormTemplateDto {
  constructor(json: JSON | any) {
    Object.assign(this as FormTemplateDto, json)
  }

  id?: string
  rev?: string
  deletionDate?: number
  layout?: FormLayout
  name?: string
  guid?: string
  group?: DocumentGroupDto
  descr?: string
  disabled?: string
  specialty?: CodeStubDto
  author?: string
  formInstancePreferredLocation?: string
  keyboardShortcut?: string
  shortReport?: string
  mediumReport?: string
  longReport?: string
  reports?: Array<string>
  tags?: Array<CodeStubDto>
  layoutAttachmentId?: string
}
