/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from "./Address"
import { CodeStub } from "./CodeStub"
import { FinancialInstitutionInformation } from "./FinancialInstitutionInformation"
import { FlatRateTarification } from "./FlatRateTarification"

import { decodeBase64 } from "./ModelHelper"

export class HealthcareParty {
  constructor(json: JSON | any) {
    Object.assign(
      this as HealthcareParty,
      json,
      json.picture ? { picture: decodeBase64(json.picture) } : {}
    )
  }

  id?: string
  rev?: string
  deletionDate?: number
  name?: string
  lastName?: string
  firstName?: string
  gender?: HealthcareParty.GenderEnum
  civility?: string
  companyName?: string
  speciality?: string
  bankAccount?: string
  bic?: string
  proxyBankAccount?: string
  proxyBic?: string
  invoiceHeader?: string
  cbe?: string
  ehp?: string
  userId?: string
  parentId?: string
  convention?: number
  nihii?: string
  nihiiSpecCode?: string
  ssin?: string
  addresses?: Array<Address>
  languages?: Array<string>
  picture?: ArrayBuffer
  statuses?: Array<HealthcareParty.StatusesEnum>
  specialityCodes?: Array<CodeStub>
  sendFormats?: { [key: string]: string }
  notes?: string
  financialInstitutionInformation?: Array<FinancialInstitutionInformation>
  billingType?: string
  type?: string
  contactPerson?: string
  contactPersonHcpId?: string
  flatRateTarifications?: Array<FlatRateTarification>
  importedData?: { [key: string]: string }
  options?: { [key: string]: string }
  hcPartyKeys?: { [key: string]: Array<string> }
  privateKeyShamirPartitions?: { [key: string]: string }
  publicKey?: string
}
export namespace HealthcareParty {
  export type GenderEnum = "M" | "F" | "I" | "C" | "Y" | "X" | "U"
  export const GenderEnum = {
    M: "M" as GenderEnum,
    F: "F" as GenderEnum,
    I: "I" as GenderEnum,
    C: "C" as GenderEnum,
    Y: "Y" as GenderEnum,
    X: "X" as GenderEnum,
    U: "U" as GenderEnum
  }
  export type StatusesEnum = "trainee" | "withconvention" | "accreditated"
  export const StatusesEnum = {
    Trainee: "trainee" as StatusesEnum,
    Withconvention: "withconvention" as StatusesEnum,
    Accreditated: "accreditated" as StatusesEnum
  }
}
