/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CareTeamMemberDto } from "./CareTeamMemberDto"
import { CodeDto } from "./CodeDto"
import { DelegationDto } from "./DelegationDto"
import { EpisodeDto } from "./EpisodeDto"
import { PlanOfActionDto } from "./PlanOfActionDto"

export class HealthElementDto {
  constructor(json: JSON | any) {
    Object.assign(this as HealthElementDto, json)
  }

  id?: string
  rev?: string
  deletionDate?: number
  created?: number
  modified?: number
  endOfLife?: number
  author?: string
  responsible?: string
  medicalLocationId?: string
  encryptedSelf?: string
  codes?: Array<CodeDto>
  tags?: Array<CodeDto>
  secretForeignKeys?: Array<string>
  cryptedForeignKeys?: { [key: string]: Array<DelegationDto> }
  delegations?: { [key: string]: Array<DelegationDto> }
  encryptionKeys?: { [key: string]: Array<DelegationDto> }
  healthElementId?: string
  descr?: string
  note?: string
  relevant?: boolean
  valueDate?: number
  openingDate?: number
  closingDate?: number
  idOpeningContact?: string
  idClosingContact?: string
  status?: number
  idService?: string
  laterality?: HealthElementDto.HealthElementDtoLateralityEnum
  plansOfAction?: Array<PlanOfActionDto>
  episodes?: Array<EpisodeDto>
  careTeam?: Array<CareTeamMemberDto>
}
export namespace HealthElementDto {
  export type HealthElementDtoLateralityEnum = "left" | "right"
  export const HealthElementDtoLateralityEnum = {
    Left: "left" as HealthElementDtoLateralityEnum,
    Right: "right" as HealthElementDtoLateralityEnum
  }
}
