/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from "./models"

export class InvoiceItem  {
  constructor(json: JSON | any) {
    Object.assign(this as InvoiceItem, json)
  }
  dateCode?: number

  codeNomenclature?: number

  relatedCode?: number

  eidItem?: models.EIDItem

  insuranceRef?: string

  insuranceRefDate?: number

  units?: number

  reimbursedAmount?: number

  patientFee?: number

  doctorSupplement?: number

  sideCode?: InvoiceItem.SideCodeEnum

  timeOfDay?: InvoiceItem.TimeOfDayEnum

  override3rdPayerCode?: number

  gnotionNihii?: string

  derogationMaxNumber?: InvoiceItem.DerogationMaxNumberEnum

  prescriberNorm?: InvoiceItem.PrescriberNormEnum

  prescriberNihii?: string

  personalInterventionCoveredByThirdPartyCode?: number

  doctorIdentificationNumber?: string

  invoiceRef?: string

  percentNorm?: InvoiceItem.PercentNormEnum
}
export namespace InvoiceItem {
  export enum SideCodeEnum {
    None = <any>"None",
    Left = <any>"Left",
    Right = <any>"Right"
  }
  export enum TimeOfDayEnum {
    Other = <any>"Other",
    Night = <any>"Night",
    Weekend = <any>"Weekend",
    Bankholiday = <any>"Bankholiday",
    Urgent = <any>"Urgent"
  }
  export enum DerogationMaxNumberEnum {
    Other = <any>"Other",
    DerogationMaxNumber = <any>"DerogationMaxNumber",
    OtherPrescription = <any>"OtherPrescription",
    SecondPrestationOfDay = <any>"SecondPrestationOfDay",
    ThirdAndNextPrestationOfDay = <any>"ThirdAndNextPrestationOfDay"
  }
  export enum PrescriberNormEnum {
    None = <any>"None",
    OnePrescriber = <any>"OnePrescriber",
    SelfPrescriber = <any>"SelfPrescriber",
    AddedCode = <any>"AddedCode",
    ManyPrescribers = <any>"ManyPrescribers"
  }
  export enum PercentNormEnum {
    None = <any>"None",
    SurgicalAid1 = <any>"SurgicalAid1",
    SurgicalAid2 = <any>"SurgicalAid2",
    ReducedFee = <any>"ReducedFee",
    Ah1n1 = <any>"Ah1n1",
    HalfPriceSecondAct = <any>"HalfPriceSecondAct",
    InvoiceException = <any>"InvoiceException",
    ForInformation = <any>"ForInformation"
  }
}
