/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EIDItem } from "./EIDItem"

export class InvoiceItem {
  constructor(json: JSON | any) {
    Object.assign(this as InvoiceItem, json)
  }

  dateCode?: number
  codeNomenclature?: number
  relatedCode?: number
  eidItem?: EIDItem
  insuranceRef?: string
  insuranceRefDate?: number
  units?: number
  reimbursedAmount?: number
  patientFee?: number
  doctorSupplement?: number
  sideCode?: InvoiceItem.InvoiceItemSideCodeEnum
  timeOfDay?: InvoiceItem.InvoiceItemTimeOfDayEnum
  override3rdPayerCode?: number
  gnotionNihii?: string
  derogationMaxNumber?: InvoiceItem.InvoiceItemDerogationMaxNumberEnum
  prescriberNorm?: InvoiceItem.InvoiceItemPrescriberNormEnum
  prescriberNihii?: string
  personalInterventionCoveredByThirdPartyCode?: number
  doctorIdentificationNumber?: string
  invoiceRef?: string
  percentNorm?: InvoiceItem.InvoiceItemPercentNormEnum
}
export namespace InvoiceItem {
  export type InvoiceItemSideCodeEnum = "None" | "Left" | "Right"
  export const InvoiceItemSideCodeEnum = {
    None: "None" as InvoiceItemSideCodeEnum,
    Left: "Left" as InvoiceItemSideCodeEnum,
    Right: "Right" as InvoiceItemSideCodeEnum
  }
  export type InvoiceItemTimeOfDayEnum = "Other" | "Night" | "Weekend" | "Bankholiday" | "Urgent"
  export const InvoiceItemTimeOfDayEnum = {
    Other: "Other" as InvoiceItemTimeOfDayEnum,
    Night: "Night" as InvoiceItemTimeOfDayEnum,
    Weekend: "Weekend" as InvoiceItemTimeOfDayEnum,
    Bankholiday: "Bankholiday" as InvoiceItemTimeOfDayEnum,
    Urgent: "Urgent" as InvoiceItemTimeOfDayEnum
  }
  export type InvoiceItemDerogationMaxNumberEnum =
    | "Other"
    | "DerogationMaxNumber"
    | "OtherPrescription"
    | "SecondPrestationOfDay"
    | "ThirdAndNextPrestationOfDay"
  export const InvoiceItemDerogationMaxNumberEnum = {
    Other: "Other" as InvoiceItemDerogationMaxNumberEnum,
    DerogationMaxNumber: "DerogationMaxNumber" as InvoiceItemDerogationMaxNumberEnum,
    OtherPrescription: "OtherPrescription" as InvoiceItemDerogationMaxNumberEnum,
    SecondPrestationOfDay: "SecondPrestationOfDay" as InvoiceItemDerogationMaxNumberEnum,
    ThirdAndNextPrestationOfDay: "ThirdAndNextPrestationOfDay" as InvoiceItemDerogationMaxNumberEnum
  }
  export type InvoiceItemPrescriberNormEnum =
    | "None"
    | "OnePrescriber"
    | "SelfPrescriber"
    | "AddedCode"
    | "ManyPrescribers"
  export const InvoiceItemPrescriberNormEnum = {
    None: "None" as InvoiceItemPrescriberNormEnum,
    OnePrescriber: "OnePrescriber" as InvoiceItemPrescriberNormEnum,
    SelfPrescriber: "SelfPrescriber" as InvoiceItemPrescriberNormEnum,
    AddedCode: "AddedCode" as InvoiceItemPrescriberNormEnum,
    ManyPrescribers: "ManyPrescribers" as InvoiceItemPrescriberNormEnum
  }
  export type InvoiceItemPercentNormEnum =
    | "None"
    | "SurgicalAid1"
    | "SurgicalAid2"
    | "ReducedFee"
    | "Ah1n1"
    | "HalfPriceSecondAct"
    | "InvoiceException"
    | "ForInformation"
  export const InvoiceItemPercentNormEnum = {
    None: "None" as InvoiceItemPercentNormEnum,
    SurgicalAid1: "SurgicalAid1" as InvoiceItemPercentNormEnum,
    SurgicalAid2: "SurgicalAid2" as InvoiceItemPercentNormEnum,
    ReducedFee: "ReducedFee" as InvoiceItemPercentNormEnum,
    Ah1n1: "Ah1n1" as InvoiceItemPercentNormEnum,
    HalfPriceSecondAct: "HalfPriceSecondAct" as InvoiceItemPercentNormEnum,
    InvoiceException: "InvoiceException" as InvoiceItemPercentNormEnum,
    ForInformation: "ForInformation" as InvoiceItemPercentNormEnum
  }
}
