/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeDto } from "./CodeDto"
import { DelegationDto } from "./DelegationDto"
import { MessageReadStatus } from "./MessageReadStatus"

export class MessageDto {
  constructor(json: JSON | any) {
    Object.assign(this as MessageDto, json)
  }

  id?: string
  rev?: string
  deletionDate?: number
  created?: number
  modified?: number
  endOfLife?: number
  author?: string
  responsible?: string
  medicalLocationId?: string
  encryptedSelf?: string
  codes?: Array<CodeDto>
  tags?: Array<CodeDto>
  secretForeignKeys?: Array<string>
  cryptedForeignKeys?: { [key: string]: Array<DelegationDto> }
  delegations?: { [key: string]: Array<DelegationDto> }
  encryptionKeys?: { [key: string]: Array<DelegationDto> }
  fromAddress?: string
  fromHealthcarePartyId?: string
  formId?: string
  status?: number
  recipientsType?: string
  recipients?: Array<string>
  toAddresses?: Array<string>
  received?: number
  sent?: number
  metas?: { [key: string]: string }
  readStatus?: { [key: string]: MessageReadStatus }
  transportGuid?: string
  remark?: string
  conversationGuid?: string
  subject?: string
  invoiceIds?: Array<string>
  parentId?: string
  externalRef?: string
  senderReferences?: { [key: string]: string }
  unassignedResults?: Array<string>
  assignedResults?: { [key: string]: string }
}
