/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeStub } from "./CodeStub"
import { Delegation } from "./Delegation"
import { MessageReadStatus } from "./MessageReadStatus"

import { decodeBase64 } from "./ModelHelper"

export class Message {
  constructor(json: JSON | any) {
    Object.assign(this as Message, json)
  }

  id?: string
  rev?: string
  created?: number
  modified?: number
  author?: string
  responsible?: string
  medicalLocationId?: string
  tags?: Array<CodeStub>
  codes?: Array<CodeStub>
  endOfLife?: number
  deletionDate?: number
  fromAddress?: string
  fromHealthcarePartyId?: string
  formId?: string
  status?: number
  recipientsType?: string
  recipients?: Array<string>
  toAddresses?: Array<string>
  received?: number
  sent?: number
  metas?: { [key: string]: string }
  readStatus?: { [key: string]: MessageReadStatus }
  transportGuid?: string
  remark?: string
  conversationGuid?: string
  subject?: string
  invoiceIds?: Array<string>
  parentId?: string
  externalRef?: string
  unassignedResults?: Array<string>
  assignedResults?: { [key: string]: string }
  senderReferences?: { [key: string]: string }
  secretForeignKeys?: Array<string>
  cryptedForeignKeys?: { [key: string]: Array<Delegation> }
  delegations?: { [key: string]: Array<Delegation> }
  encryptionKeys?: { [key: string]: Array<Delegation> }
  encryptedSelf?: string
}
