/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class PartnershipDto {
  constructor(json: JSON | any) {
    Object.assign(this as PartnershipDto, json)
  }

  partnershipDescription?: string
  type?: PartnershipDto.PartnershipDtoTypeEnum
  status?: PartnershipDto.PartnershipDtoStatusEnum
  meToOtherRelationshipDescription?: string
  otherToMeRelationshipDescription?: string
  partnerId?: string
}
export namespace PartnershipDto {
  export type PartnershipDtoTypeEnum =
    | "primary_contact"
    | "primary_contact_for"
    | "tutor"
    | "family"
    | "friend"
    | "counselor"
    | "contact"
  export const PartnershipDtoTypeEnum = {
    PrimaryContact: "primary_contact" as PartnershipDtoTypeEnum,
    PrimaryContactFor: "primary_contact_for" as PartnershipDtoTypeEnum,
    Tutor: "tutor" as PartnershipDtoTypeEnum,
    Family: "family" as PartnershipDtoTypeEnum,
    Friend: "friend" as PartnershipDtoTypeEnum,
    Counselor: "counselor" as PartnershipDtoTypeEnum,
    Contact: "contact" as PartnershipDtoTypeEnum
  }
  export type PartnershipDtoStatusEnum = "active" | "complicated" | "past"
  export const PartnershipDtoStatusEnum = {
    Active: "active" as PartnershipDtoStatusEnum,
    Complicated: "complicated" as PartnershipDtoStatusEnum,
    Past: "past" as PartnershipDtoStatusEnum
  }
}
