/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from "./Address"
import { CodeStub } from "./CodeStub"
import { Delegation } from "./Delegation"
import { EmploymentInfo } from "./EmploymentInfo"
import { FinancialInstitutionInformation } from "./FinancialInstitutionInformation"
import { Insurability } from "./Insurability"
import { MedicalHouseContract } from "./MedicalHouseContract"
import { Partnership } from "./Partnership"
import { PatientHealthCareParty } from "./PatientHealthCareParty"
import { PropertyStub } from "./PropertyStub"
import { SchoolingInfo } from "./SchoolingInfo"

import { decodeBase64 } from "./ModelHelper"

export class Patient {
  constructor(json: JSON | any) {
    Object.assign(
      this as Patient,
      json,
      json.picture ? { picture: decodeBase64(json.picture) } : {}
    )
  }

  id?: string
  rev?: string
  created?: number
  modified?: number
  author?: string
  responsible?: string
  medicalLocationId?: string
  tags?: Array<CodeStub>
  codes?: Array<CodeStub>
  endOfLife?: number
  deletionDate?: number
  firstName?: string
  lastName?: string
  companyName?: string
  languages?: Array<string>
  addresses?: Array<Address>
  civility?: string
  gender?: Patient.GenderEnum
  mergeToPatientId?: string
  mergedIds?: Array<string>
  nonDuplicateIds?: Array<string>
  encryptedAdministrativesDocuments?: Array<string>
  alias?: string
  active?: boolean
  deactivationReason?: Patient.DeactivationReasonEnum
  ssin?: string
  maidenName?: string
  spouseName?: string
  partnerName?: string
  personalStatus?: Patient.PersonalStatusEnum
  dateOfBirth?: number
  dateOfDeath?: number
  timestampOfLatestEidReading?: number
  placeOfBirth?: string
  placeOfDeath?: string
  education?: string
  profession?: string
  note?: string
  administrativeNote?: string
  comment?: string
  warning?: string
  nationality?: string
  preferredUserId?: string
  picture?: ArrayBuffer
  externalId?: string
  insurabilities?: Array<Insurability>
  partnerships?: Array<Partnership>
  patientHealthCareParties?: Array<PatientHealthCareParty>
  financialInstitutionInformation?: Array<FinancialInstitutionInformation>
  medicalHouseContracts?: Array<MedicalHouseContract>
  parameters?: { [key: string]: Array<string> }
  patientProfessions?: Array<CodeStub>
  fatherBirthCountry?: CodeStub
  birthCountry?: CodeStub
  nativeCountry?: CodeStub
  socialStatus?: CodeStub
  mainSourceOfIncome?: CodeStub
  schoolingInfos?: Array<SchoolingInfo>
  employementInfos?: Array<EmploymentInfo>
  properties?: Array<PropertyStub>
  hcPartyKeys?: { [key: string]: Array<string> }
  privateKeyShamirPartitions?: { [key: string]: string }
  publicKey?: string
  secretForeignKeys?: Array<string>
  cryptedForeignKeys?: { [key: string]: Array<Delegation> }
  delegations?: { [key: string]: Array<Delegation> }
  encryptionKeys?: { [key: string]: Array<Delegation> }
  encryptedSelf?: string
}
export namespace Patient {
  export type GenderEnum = "M" | "F" | "I" | "C" | "Y" | "X" | "U"
  export const GenderEnum = {
    M: "M" as GenderEnum,
    F: "F" as GenderEnum,
    I: "I" as GenderEnum,
    C: "C" as GenderEnum,
    Y: "Y" as GenderEnum,
    X: "X" as GenderEnum,
    U: "U" as GenderEnum
  }
  export type DeactivationReasonEnum =
    | "deceased"
    | "moved"
    | "other_doctor"
    | "retired"
    | "no_contact"
    | "unknown"
    | "none"
  export const DeactivationReasonEnum = {
    Deceased: "deceased" as DeactivationReasonEnum,
    Moved: "moved" as DeactivationReasonEnum,
    OtherDoctor: "other_doctor" as DeactivationReasonEnum,
    Retired: "retired" as DeactivationReasonEnum,
    NoContact: "no_contact" as DeactivationReasonEnum,
    Unknown: "unknown" as DeactivationReasonEnum,
    None: "none" as DeactivationReasonEnum
  }
  export type PersonalStatusEnum =
    | "single"
    | "in_couple"
    | "married"
    | "separated"
    | "divorced"
    | "divorcing"
    | "widowed"
    | "widower"
    | "complicated"
    | "unknown"
    | "contract"
    | "other"
  export const PersonalStatusEnum = {
    Single: "single" as PersonalStatusEnum,
    InCouple: "in_couple" as PersonalStatusEnum,
    Married: "married" as PersonalStatusEnum,
    Separated: "separated" as PersonalStatusEnum,
    Divorced: "divorced" as PersonalStatusEnum,
    Divorcing: "divorcing" as PersonalStatusEnum,
    Widowed: "widowed" as PersonalStatusEnum,
    Widower: "widower" as PersonalStatusEnum,
    Complicated: "complicated" as PersonalStatusEnum,
    Unknown: "unknown" as PersonalStatusEnum,
    Contract: "contract" as PersonalStatusEnum,
    Other: "other" as PersonalStatusEnum
  }
}
