/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class Payment {
  constructor(json: JSON | any) {
    Object.assign(this as Payment, json)
  }

  paymentDate?: number
  paymentType?: Payment.PaymentPaymentTypeEnum
  paid?: number
}
export namespace Payment {
  export type PaymentPaymentTypeEnum =
    | "cash"
    | "wired"
    | "insurance"
    | "creditcard"
    | "debitcard"
    | "paypal"
    | "bitcoin"
    | "other"
  export const PaymentPaymentTypeEnum = {
    Cash: "cash" as PaymentPaymentTypeEnum,
    Wired: "wired" as PaymentPaymentTypeEnum,
    Insurance: "insurance" as PaymentPaymentTypeEnum,
    Creditcard: "creditcard" as PaymentPaymentTypeEnum,
    Debitcard: "debitcard" as PaymentPaymentTypeEnum,
    Paypal: "paypal" as PaymentPaymentTypeEnum,
    Bitcoin: "bitcoin" as PaymentPaymentTypeEnum,
    Other: "other" as PaymentPaymentTypeEnum
  }
}
