/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class PermissionCriterion {
  constructor(json: JSON | any) {
    Object.assign(this as PermissionCriterion, json)
  }

  negative?: boolean
  currentUser?: PermissionCriterion.PermissionCriterionCurrentUserEnum
  dataType?: PermissionCriterion.PermissionCriterionDataTypeEnum
  patientStatus?: string
  useless?: boolean
  type?: PermissionCriterion.PermissionCriterionTypeEnum
}
export namespace PermissionCriterion {
  export type PermissionCriterionCurrentUserEnum =
    | "DATA_CREATION_USER"
    | "DATA_MODIFICATION_USER"
    | "PATIENT_CREATION_USER"
    | "PATIENT_MODIFICATION_USER"
    | "PATIENT_REFERENCE_HC_USER"
    | "PATIENT_HC_TEAM_USER"
  export const PermissionCriterionCurrentUserEnum = {
    DATACREATIONUSER: "DATA_CREATION_USER" as PermissionCriterionCurrentUserEnum,
    DATAMODIFICATIONUSER: "DATA_MODIFICATION_USER" as PermissionCriterionCurrentUserEnum,
    PATIENTCREATIONUSER: "PATIENT_CREATION_USER" as PermissionCriterionCurrentUserEnum,
    PATIENTMODIFICATIONUSER: "PATIENT_MODIFICATION_USER" as PermissionCriterionCurrentUserEnum,
    PATIENTREFERENCEHCUSER: "PATIENT_REFERENCE_HC_USER" as PermissionCriterionCurrentUserEnum,
    PATIENTHCTEAMUSER: "PATIENT_HC_TEAM_USER" as PermissionCriterionCurrentUserEnum
  }
  export type PermissionCriterionDataTypeEnum =
    | "ADMINISTRATIVE"
    | "HEALTH"
    | "SENSITIVE"
    | "CONFIDENTIAL"
  export const PermissionCriterionDataTypeEnum = {
    ADMINISTRATIVE: "ADMINISTRATIVE" as PermissionCriterionDataTypeEnum,
    HEALTH: "HEALTH" as PermissionCriterionDataTypeEnum,
    SENSITIVE: "SENSITIVE" as PermissionCriterionDataTypeEnum,
    CONFIDENTIAL: "CONFIDENTIAL" as PermissionCriterionDataTypeEnum
  }
  export type PermissionCriterionTypeEnum =
    | "VIRTUALHOST"
    | "CURRENT_USER"
    | "DATA_TYPE"
    | "PATIENT_STATUS"
  export const PermissionCriterionTypeEnum = {
    VIRTUALHOST: "VIRTUALHOST" as PermissionCriterionTypeEnum,
    CURRENTUSER: "CURRENT_USER" as PermissionCriterionTypeEnum,
    DATATYPE: "DATA_TYPE" as PermissionCriterionTypeEnum,
    PATIENTSTATUS: "PATIENT_STATUS" as PermissionCriterionTypeEnum
  }
}
