/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PropertyTypeStubDto } from "./PropertyTypeStubDto"
import { TypedValueDtoObject } from "./TypedValueDtoObject"

export class PropertyStubDto {
  constructor(json: JSON | any) {
    Object.assign(this as PropertyStubDto, json)
  }

  type?: PropertyTypeStubDto
  typedValue?: TypedValueDtoObject
}
