/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class RegistrationInformation {
  constructor(json: JSON | any) {
    Object.assign(this as RegistrationInformation, json)
  }

  firstName?: string
  lastName?: string
  emailAddress?: string
  userOptions?: { [key: string]: string }
}
