/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CopaymentDto } from "./CopaymentDto"
import { PricingDto } from "./PricingDto"
import { ReimbursementCriterionDto } from "./ReimbursementCriterionDto"

export class ReimbursementDto {
  constructor(json: JSON | any) {
    Object.assign(this as ReimbursementDto, json)
  }

  from?: number
  to?: number
  deliveryEnvironment?: ReimbursementDto.ReimbursementDtoDeliveryEnvironmentEnum
  code?: string
  codeType?: ReimbursementDto.ReimbursementDtoCodeTypeEnum
  multiple?: ReimbursementDto.ReimbursementDtoMultipleEnum
  temporary?: boolean
  reference?: boolean
  flatRateSystem?: boolean
  reimbursementBasePrice?: number
  referenceBasePrice?: number
  copaymentSupplement?: number
  pricingUnit?: PricingDto
  pricingSlice?: PricingDto
  reimbursementCriterion?: ReimbursementCriterionDto
  copayments?: Array<CopaymentDto>
}
export namespace ReimbursementDto {
  export type ReimbursementDtoDeliveryEnvironmentEnum = "P" | "A" | "H" | "R"
  export const ReimbursementDtoDeliveryEnvironmentEnum = {
    P: "P" as ReimbursementDtoDeliveryEnvironmentEnum,
    A: "A" as ReimbursementDtoDeliveryEnvironmentEnum,
    H: "H" as ReimbursementDtoDeliveryEnvironmentEnum,
    R: "R" as ReimbursementDtoDeliveryEnvironmentEnum
  }
  export type ReimbursementDtoCodeTypeEnum = "CNK" | "PSEUDO"
  export const ReimbursementDtoCodeTypeEnum = {
    CNK: "CNK" as ReimbursementDtoCodeTypeEnum,
    PSEUDO: "PSEUDO" as ReimbursementDtoCodeTypeEnum
  }
  export type ReimbursementDtoMultipleEnum = "M" | "V"
  export const ReimbursementDtoMultipleEnum = {
    M: "M" as ReimbursementDtoMultipleEnum,
    V: "V" as ReimbursementDtoMultipleEnum
  }
}
