/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DurationDto } from "./DurationDto"

import { decodeBase64 } from "./ModelHelper"

export class RenewalDto {
  constructor(json: JSON | any) {
    Object.assign(this as RenewalDto, json)
  }

  decimal?: number
  duration?: DurationDto
}
