/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * List of all services provided to the patient under a given contact which is linked by this sub-contact to other structuring elements.
 */
export class ServiceLink {
  constructor(json: JSON | any) {
    Object.assign(this as ServiceLink, json)
  }

  serviceId?: string
}
