/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NumeratorRange } from "./NumeratorRange"
import { Quantity } from "./Quantity"

import { decodeBase64 } from "./ModelHelper"

export class StrengthRange {
  constructor(json: JSON | any) {
    Object.assign(this as StrengthRange, json)
  }

  numeratorRange?: NumeratorRange
  denominator?: Quantity
}
