/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SamText } from "./SamText"
import { StandardSubstance } from "./StandardSubstance"

import { decodeBase64 } from "./ModelHelper"

export class Substance {
  constructor(json: JSON | any) {
    Object.assign(this as Substance, json)
  }

  id?: string
  rev?: string
  deletionDate?: number
  code?: string
  chemicalForm?: string
  name?: SamText
  note?: SamText
  standardSubstances?: Array<StandardSubstance>
}
