/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class TelecomDtoEmbed {
  constructor(json: JSON | any) {
    Object.assign(this as TelecomDtoEmbed, json)
  }

  telecomType?: TelecomDtoEmbed.TelecomDtoEmbedTelecomTypeEnum
  telecomNumber?: string
  telecomDescription?: string
  encryptedSelf?: string
}
export namespace TelecomDtoEmbed {
  export type TelecomDtoEmbedTelecomTypeEnum =
    | "mobile"
    | "phone"
    | "email"
    | "fax"
    | "skype"
    | "im"
    | "medibridge"
    | "ehealthbox"
    | "apicrypt"
    | "web"
    | "print"
    | "disk"
  export const TelecomDtoEmbedTelecomTypeEnum = {
    Mobile: "mobile" as TelecomDtoEmbedTelecomTypeEnum,
    Phone: "phone" as TelecomDtoEmbedTelecomTypeEnum,
    Email: "email" as TelecomDtoEmbedTelecomTypeEnum,
    Fax: "fax" as TelecomDtoEmbedTelecomTypeEnum,
    Skype: "skype" as TelecomDtoEmbedTelecomTypeEnum,
    Im: "im" as TelecomDtoEmbedTelecomTypeEnum,
    Medibridge: "medibridge" as TelecomDtoEmbedTelecomTypeEnum,
    Ehealthbox: "ehealthbox" as TelecomDtoEmbedTelecomTypeEnum,
    Apicrypt: "apicrypt" as TelecomDtoEmbedTelecomTypeEnum,
    Web: "web" as TelecomDtoEmbedTelecomTypeEnum,
    Print: "print" as TelecomDtoEmbedTelecomTypeEnum,
    Disk: "disk" as TelecomDtoEmbedTelecomTypeEnum
  }
}
