/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PermissionDto } from "./PermissionDto"
import { PropertyDto } from "./PropertyDto"

export class UserDto {
  constructor(json: JSON | any) {
    Object.assign(this as UserDto, json)
  }

  id?: string
  rev?: string
  deletionDate?: number
  name?: string
  properties?: Array<PropertyDto>
  permissions?: Array<PermissionDto>
  type?: UserDto.UserDtoTypeEnum
  status?: UserDto.UserDtoStatusEnum
  groupId?: string
  login?: string
  password?: string
  passwordHash?: string
  secret?: string
  use2fa?: boolean
  createdDate?: number
  lastLoginDate?: number
  expirationDate?: number
  activationToken?: string
  activationTokenExpirationDate?: number
  passwordToken?: string
  passwordTokenExpirationDate?: number
  termsOfUseDate?: number
  healthcarePartyId?: string
  patientId?: string
  roles?: Array<string>
  email?: string
  autoDelegations?: { [key: string]: Array<string> }
  applicationTokens?: { [key: string]: string }
  virtualHostDependency?: UserDto.UserDtoVirtualHostDependencyEnum
  virtualHosts?: Array<string>
}
export namespace UserDto {
  export type UserDtoTypeEnum = "database" | "ldap" | "token"
  export const UserDtoTypeEnum = {
    Database: "database" as UserDtoTypeEnum,
    Ldap: "ldap" as UserDtoTypeEnum,
    Token: "token" as UserDtoTypeEnum
  }
  export type UserDtoStatusEnum = "ACTIVE" | "DISABLED" | "REGISTERING"
  export const UserDtoStatusEnum = {
    ACTIVE: "ACTIVE" as UserDtoStatusEnum,
    DISABLED: "DISABLED" as UserDtoStatusEnum,
    REGISTERING: "REGISTERING" as UserDtoStatusEnum
  }
  export type UserDtoVirtualHostDependencyEnum = "NONE" | "DIRECT" | "FULL"
  export const UserDtoVirtualHostDependencyEnum = {
    NONE: "NONE" as UserDtoVirtualHostDependencyEnum,
    DIRECT: "DIRECT" as UserDtoVirtualHostDependencyEnum,
    FULL: "FULL" as UserDtoVirtualHostDependencyEnum
  }
}
