/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class VirtualHostDto {
  constructor(json: JSON | any) {
    Object.assign(this as VirtualHostDto, json)
  }

  id?: string
  rev?: string
  deletionDate?: number
  identifier?: string
  hostnames?: string
  anonymousRole?: string
  configuration?: string
  roles?: Array<string>
  hostnamesList?: Array<string>
}
