/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StrengthRangeDto } from "./StrengthRangeDto"
import { SubstanceStubDto } from "./SubstanceStubDto"

import { decodeBase64 } from "./ModelHelper"

export class VirtualIngredientDto {
  constructor(json: JSON | any) {
    Object.assign(this as VirtualIngredientDto, json)
  }

  from?: number
  to?: number
  rank?: number
  type?: VirtualIngredientDto.TypeEnum
  strengthRange?: StrengthRangeDto
  substance?: SubstanceStubDto
}
export namespace VirtualIngredientDto {
  export type TypeEnum = "ACTIVE_SUBSTANCE" | "EXCIPIENT"
  export const TypeEnum = {
    ACTIVESUBSTANCE: "ACTIVE_SUBSTANCE" as TypeEnum,
    EXCIPIENT: "EXCIPIENT" as TypeEnum,
  }
}
