/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommentedClassificationDto } from "./CommentedClassificationDto"
import { SamTextDto } from "./SamTextDto"
import { VmpComponentDto } from "./VmpComponentDto"
import { VmpGroupStubDto } from "./VmpGroupStubDto"
import { VtmDto } from "./VtmDto"
import { WadaDto } from "./WadaDto"

import { decodeBase64 } from "./ModelHelper"

export class VmpDto {
  constructor(json: JSON | any) {
    Object.assign(this as VmpDto, json)
  }

  id?: string
  rev?: string
  /**
   * hard delete (unix epoch in ms) timestamp of the object. Filled automatically when deletePatient is called.
   */
  deletionDate?: number
  from?: number
  to?: number
  code?: string
  vmpGroup?: VmpGroupStubDto
  name?: SamTextDto
  abbreviation?: SamTextDto
  vtm?: VtmDto
  wadas?: Array<WadaDto>
  components?: Array<VmpComponentDto>
  commentedClassifications?: Array<CommentedClassificationDto>
}
