/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Attachment } from "./Attachment"
import { CommentedClassificationDto } from "./CommentedClassificationDto"
import { RevisionInfo } from "./RevisionInfo"
import { SamTextDto } from "./SamTextDto"
import { VmpComponentDto } from "./VmpComponentDto"
import { VmpGroupStubDto } from "./VmpGroupStubDto"
import { VtmDto } from "./VtmDto"
import { WadaDto } from "./WadaDto"

export class VmpDto {
  constructor(json: JSON | any) {
    Object.assign(this as VmpDto, json)
  }

  id?: string
  from?: number
  to?: number
  code?: string
  vmpGroup?: VmpGroupStubDto
  name?: SamTextDto
  abbreviation?: SamTextDto
  vtm?: VtmDto
  wadas?: Array<WadaDto>
  components?: Array<VmpComponentDto>
  commentedClassifications?: Array<CommentedClassificationDto>
  attachments?: { [key: string]: Attachment }
  deleted?: number
  rev?: string
  revsInfo?: Array<RevisionInfo>
  conflicts?: Array<string>
  javaType?: string
  revHistory?: { [key: string]: string }
}
