/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WebSessionMaxIdleTime } from "./WebSessionMaxIdleTime"

import { decodeBase64 } from "./ModelHelper"

export class WebSession {
  constructor(json: JSON | any) {
    Object.assign(this as WebSession, json)
  }

  id?: string
  attributes?: { [key: string]: any }
  started?: boolean
  expired?: boolean
  creationTime?: number
  lastAccessTime?: number
  maxIdleTime?: WebSessionMaxIdleTime
}
