/**
 * iCure Cloud API Documentation
 * Spring shop sample application
 *
 * OpenAPI spec version: v0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XHR } from "./XHR"
import { CalendarItemTypeDto } from "../model/CalendarItemTypeDto"
import { DocIdentifier } from "../model/DocIdentifier"

export class iccCalendarItemTypeApi {
  host: string
  headers: Array<XHR.Header>
  fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>

  constructor(
    host: string,
    headers: any,
    fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>
  ) {
    this.host = host
    this.headers = Object.keys(headers).map(k => new XHR.Header(k, headers[k]))
    this.fetchImpl = fetchImpl
  }

  setHeaders(h: Array<XHR.Header>) {
    this.headers = h
  }

  handleError(e: XHR.Data) {
    if (e.status == 401) throw Error("auth-failed")
    else throw Error("api-error" + e.status)
  }

  /**
   *
   * @summary Creates a calendarItemType
   * @param body
   */
  createCalendarItemType(body?: CalendarItemTypeDto): Promise<CalendarItemTypeDto | any> {
    let _body = null
    _body = body

    const _url = this.host + "/calendarItemType" + "?ts=" + new Date().getTime()
    let headers = this.headers
    headers = headers
      .filter(h => h.header !== "Content-Type")
      .concat(new XHR.Header("Content-Type", "application/json"))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => new CalendarItemTypeDto(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   *
   * @summary Deletes an calendarItemType
   * @param calendarItemTypeIds
   */
  deleteCalendarItemType(calendarItemTypeIds: string): Promise<Array<DocIdentifier> | any> {
    let _body = null

    const _url =
      this.host +
      "/calendarItemType/${encodeURIComponent(String(calendarItemTypeIds))}".replace(
        "{calendarItemTypeIds}",
        calendarItemTypeIds + ""
      ) +
      "?ts=" +
      new Date().getTime()
    let headers = this.headers
    return XHR.sendCommand("DELETE", _url, headers, _body, this.fetchImpl)
      .then(doc => (doc.body as Array<JSON>).map(it => new DocIdentifier(it)))
      .catch(err => this.handleError(err))
  }

  /**
   *
   * @summary Gets an calendarItemType
   * @param calendarItemTypeId
   */
  getCalendarItemType(calendarItemTypeId: string): Promise<CalendarItemTypeDto | any> {
    let _body = null

    const _url =
      this.host +
      "/calendarItemType/${encodeURIComponent(String(calendarItemTypeId))}".replace(
        "{calendarItemTypeId}",
        calendarItemTypeId + ""
      ) +
      "?ts=" +
      new Date().getTime()
    let headers = this.headers
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => new CalendarItemTypeDto(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   *
   * @summary Gets all calendarItemTypes
   */
  getCalendarItemTypes(): Promise<Array<CalendarItemTypeDto> | any> {
    let _body = null

    const _url = this.host + "/calendarItemType" + "?ts=" + new Date().getTime()
    let headers = this.headers
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => (doc.body as Array<JSON>).map(it => new CalendarItemTypeDto(it)))
      .catch(err => this.handleError(err))
  }

  /**
   *
   * @summary Gets all calendarItemTypes include deleted
   */
  getCalendarItemTypesIncludeDeleted(): Promise<Array<CalendarItemTypeDto> | any> {
    let _body = null

    const _url = this.host + "/calendarItemType/includeDeleted" + "?ts=" + new Date().getTime()
    let headers = this.headers
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => (doc.body as Array<JSON>).map(it => new CalendarItemTypeDto(it)))
      .catch(err => this.handleError(err))
  }

  /**
   *
   * @summary Modifies an calendarItemType
   * @param body
   */
  modifyCalendarItemType(body?: CalendarItemTypeDto): Promise<CalendarItemTypeDto | any> {
    let _body = null
    _body = body

    const _url = this.host + "/calendarItemType" + "?ts=" + new Date().getTime()
    let headers = this.headers
    headers = headers
      .filter(h => h.header !== "Content-Type")
      .concat(new XHR.Header("Content-Type", "application/json"))
    return XHR.sendCommand("PUT", _url, headers, _body, this.fetchImpl)
      .then(doc => new CalendarItemTypeDto(doc.body as JSON))
      .catch(err => this.handleError(err))
  }
}
